server:
  port: ${SERVER_PORT:8081}
app:
  default-timezone: ${APP_DEFAULT_TIMEZONE:UTC}
  upload:
    max-file-size: ${APP_UPLOAD_MAX_FILE_SIZE:5242880} # 5MB
  jwt:
    secret: ${APP_JWT_SECRET:cu$t0mS3cR3t}
    expirationMs: ${APP_JWT_EXPIRATION_MS:3600000}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cis?currentSchema=public&serverTimezone=UTC
    username: cis
    password: CIS#2025
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

redisson:
  singleServerConfig:
    address: ${REDIS_ADDRESS:redis://127.0.0.1:6379}
    password: ${REDIS_PASSWORD:admin@123}
    database: ${REDIS_DATABASE:0}

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE